### ISSUE TITLE
Display Customers that haven't placed an Order

### ISSUE THREAD

**Issue by gregkorte** [Lethal-Lemurs/Bangazon-Api#16]
By using the URL parameter `/customers/?active=false`, the JSON response should only contain customers that don't have any orders placed yet.

- [x] Enable us to select the right table and parse it for null orders.
- [x] Return the users with null orders.

**Comment by Staffmaster00** [comment]
If a join users with customers returns null return that customer.

**Comment by Staffmaster00** [comment]
https://coursework.vschool.io/express-params-and-query/
